### ISSUE TITLE
after update beetlex cannot run program with release mode

### ISSUE THREAD

**Issue by mbtolou** [beetlex-io/FastHttpApi#192]
```
    <PackageReference Include="BeetleX" Version="1.8.9.707" />
    <PackageReference Include="BeetleX.FastHttpApi" Version="2.2.22.188" />
```

Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_Name' in type 'BeetleX.FastHttpApi.HttpPacket' from assembly 'BeetleX.FastHttpApi, Version=2.2.22.188, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Mdm.Api.Authentication.AttributesManager.<>c.<GetMethodsWithToken>b__2_4(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Mdm.Api.Authentication.AttributesManager.GetMethodsWithToken(String AttributeID)
   at Mdm.Api.Authentication.AttributesManager.PopulateInfoArray()
   at Mdm.Api.Program.Main(String[] args)
   at Mdm.Api.Program.<Main>(String[] args)
System.TypeLoadException: Method 'get_Name' in type 'BeetleX.FastHttpApi.HttpPacket' from assembly 'BeetleX.FastHttpApi, Version=2.2.22.188, Culture=neutral, PublicKeyToken=null' does not have an implementatio

**Comment by mbtolou** [comment]
>>10:04:59 [Error  ] [SYSTEM] HTTP open error Method 'get_Name' in type 'BeetleX.FastHttpApi.HttpPacket' from assembly 'BeetleX.FastHttpApi, Version=2.2.22.188, Culture=neutral, PublicKeyToken=null' does not have an implementation.@   at BeetleX.FastHttpApi.HttpApiServer.OnOpen()
   at BeetleX.FastHttpApi.HttpApiServer.<Open>b__158_0()!
